[package]
name = "red-neuronal-hopfield"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "2.0.1"
getopts = "0.2.21"
image = "0.24.7"
nalgebra = "0.32.3"
rand = "0.8.5"
